### ISSUE TITLE
Documentation for ArgoCD integration problem

### ISSUE THREAD

**Issue by chrodriguez** [jkroepke/helm-secrets#350] opened 2023-03-02 12:00 UTC
### Current Behavior

When trying to build a custom image using provided Dockerfile, or even trying to set an initContainer downloading custom-tools, both failed to generate helm secrets wrapper. It seems that printf usage fails when using printf positional arguments format. 

### Expected Behavior

Get a usable initContainer or container image

### Steps To Reproduce

```markdown
1. Generate a Dockerfile

  * Copy suggested code from [documentation](https://github.com/jkroepke/helm-secrets/blob/main/docs/ArgoCD%20Integration.md#option-1-custom-docker-image)
  * Paste it into a local `Dockerfile`
  * run `docker build .`

2. Use an initContainer

  * Copy suggested code from [documentation](https://github.com/jkroepke/helm-secrets/blob/main/docs/ArgoCD%20Integration.md#option-2-init-container)
  * Paste it into a local values.yaml file
  * Install/upgrade argocd helm chart
```

### Environment

- Helm Version: n/a
- Helm Secrets Version: main branch
- ArgoCD Version: n/a
- OS: n/a
- Shell: n/a

**Comment by jkroepke** [comment] 2023-03-02 13:19
@chrodriguez Duplicate of https://github.com/jkroepke/helm-secrets/issues/349 ?

**Closed** 2023-03-06 18:53 UTC
Labels: bug
