### ISSUE TITLE
HELM_SECRETS_EVALUATE_TEMPLATES not working when using Helm Wrapper

### ISSUE THREAD

**Issue by xmath279** [jkroepke/helm-secrets#365] opened 2023-05-11 19:22 UTC
### Current Behavior

I was hoping to use the template evaluation feature using Argo CD, but to my surprise, the environment variable does not seem to be taken into account when using the wrapper.

The feature works fine when using helm secrets template <...>, but when using helm template, only the keys from the value files are retrieved. I was able to reproduce that without Argo CD by setting `HELM_SECRETS_WRAPPER_ENABLED=true` and running `helm template <...> -f secrets://values.yaml`.

### Expected Behavior

The evaluate template feature should work fine when using the wrapper feature

### Steps To Reproduce

- Set variable `HELM_SECRETS_WRAPPER_ENABLED=true`
- Create a ConfigMap that uses `ref+azurekeyvault://<...>` (or any other supported backend)
- Run helm template <...> -f secrets://values.yaml
- The generated manifests will not include the secrets from the backend (it will instead include the raw string from the template (`ref+azurekeyvault://<...>`)

### Environment

- Helm Version:v3.11.1
- Helm Secrets Version: 4.4.1-dev
- ArgoCD Version: Not relevant
- OS: Linux / macOS
- Shell: zsh / Bash

**Comment by jkroepke** [comment] 2023-05-12 05:03
If `HELM_SECRETS_WRAPPER_ENABLED=true`, then ArgoCD should call `helm secrets template <...>` and `helm template <...> -f secrets://values.yaml` with `HELM_SECRETS_EVALUATE_TEMPLATES` should work

**Comment by xmath279** [comment] 2023-05-15 14:32
Thank you for your reply. I was missing a step that you changed in the Dockerfile after my initial install (symlink to the wrapper).

I'm still getting another error, however. When Argo CD executes standard helm commands (such as helm dependency build), it fails with the following:

```
rpc error: code = Unknown desc = `helm dependency build` failed exit status 1: Error: unknown flag: --post-renderer Error: plugin "secrets" exited with error
```

I added this to the wrapper and it gets further, but I suppose I should not have to do that:

```sh
if [ "$1" = "registry" ] || [ "$1" = "env" ] || [ "$1" = "repo" ] || [ "$1" = "dependency" ]; then
  exec "${HELM_SECRETS_HELM_PATH:-${HELM_BIN:-"helm"}}" "$@"
fi
```

But even with that, I still get an error related to Azure Managed Identities (Azure CLI not found in PATH) which I don't get if I don't use the wrapper.

**Comment by jkroepke** [comment] 2023-05-15 15:17
> (Azure CLI not found in PATH)

This an follow-up issue. It seems like the wrapper is working and vals is calling here. How ever it seems like there are no credentials configured as environment variables. If no environment variables are present, the Azure SDK tries to call az cli by default.

**Comment by jkroepke** [comment] 2023-05-15 17:05
> Is there any difference with how the plugin works when not using the wrapper when it comes to calling vals?

There is only one code fragment which is calling vals. plugin caller, wrapper and post render functions are calling the same code function on the same way.

Can you test what happens if you remove the `exec` on the wrapper script?
Can you test what happens, if you are using your current working method together with the wrapper?

something like `helm secrets template -f secrets://` is still supported.

**Comment by xmath279** [comment] 2023-05-15 17:44
Just tested:

- Without `exec`: same result
- With wrapper, without `HELM_SECRETS_EVALUATE_TEMPLATES`: works, but values in templates are not replaced (values in value files are properly replaced with the correct value).
- Without wrapper: works as well, but evaluating templates is not an option in this setup.

**Comment by jkroepke** [comment] 2023-05-15 20:41
I added some test to reproduce the behavior. Tests are green. Inside CI, the use case here works in general. At least in Github Actions.

Setting an Environment variable, calling the helm wrapper.sh with HELM_SECRETS_WRAPPER_ENABLED=true and using `envsubst://` to receive the value with vals using the post-renderer options. The tests are green here.

Can you re-produce the error on the container command line without using ArgoCD? 
Did you do always a 'hard refresh' on ArgoCD Application? By default, ArgoCD is caching the generated error for 24h.

**Comment by xmath279** [comment] 2023-05-16 15:47
I was able to do some more manual testing today and was able to get it working with a shorter list of secrets to retrieve from KeyVault.

The one that I have a problem with contains around 30 Kubernetes Secrets (each with two Azure KeyVault secrets) and for some reason, the managed identity request times out. Can it be ratelimiting? Is the token endpoint called for each secret individually?

If I try the command multiple times, I am able to get the template generated after the proper values, but most of the time, I get the request timed out error.

The relevant error (I think) is `ManagedIdentityCredential: IMDS token request timed out`.

**Comment by jkroepke** [comment] 2023-05-16 17:19
If `HELM_SECRETS_WRAPPER_ENABLED =true`, vals will be called for each value file that contains `ref+` and vals is additionally called for `HELM_SECRETS_EVALUATE_TEMPLATES=true` once.

Clients to Azure KeyVault are not cached between the separate vals calls, but the token endpoint will be called for each Azure KeyVault separately.

**Comment by jkroepke** [comment] 2023-05-16 18:00
Are you able to reproduce the issue by running a

```
helm template . | vals eval 
```

In this case, its guaranteed that the root cause is out of scope of helm-secrets.

**Comment by xmath279** [comment] 2023-05-16 18:22
Yes, I am able to reproduce the issue with the vals command directly. You are right, this is out of scope of helm-secrets.

I really appreciate your time with this even if in the end it seems to be a vals / azure go sdk issue.

You can close this issue!

**Comment by jkroepke** [comment] 2023-05-16 18:27
The vals maintainer are very friendly, too. Feel free to raise an issue on vals.

**Closed** 2023-05-16 18:26 UTC
Labels: bug

**Comment by newbenji-av** [comment] 2023-06-22 11:32
seem we get this error to in argocd
